development: &DEVELOPMENT
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: wantwillwont_development
  pool: 5
  username: 
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: wantwillwont_test
  pool: 5
  username: 
  password:
  host: localhost

cucumber:
  <<: *test
